### ISSUE TITLE
Columns aren't populating

### ISSUE THREAD

**Issue by danipowers** [utkwdn/utksds-plugin#12]
When using the column block, it still populates in one line and not columns.

**Comment by pikemurdy** [comment]
Hey Dani, can you explain this? or provide screenshots, I'm not sure I follow.

**Comment by danipowers** [comment]
<img width="1491" alt="Screen Shot 2022-01-12 at 11 12 06 AM" src="https://user-images.githubusercontent.com/97196996/149178083-77f0b33d-146a-4b2a-ab28-b2c2f53229c4.png">
<img width="1558" alt="Screen Shot 2022-01-12 at 11 12 21 AM" src="https://user-images.githubusercontent.com/97196996/149178091-bece46da-739d-46cc-8137-f8f2926cc3de.png">

**Comment by danipowers** [comment]
UPDATE:
This might have been solved by whatever you did to add the missing components to the plugin - seems to be working fine now
