### ISSUE TITLE
Aligning images - they drop out. Also orange frame issue

### ISSUE THREAD

**Issue by danipowers** [utkwdn/utksds-plugin#20]
When I add an image and choose alignment for it, it seems to drop out when I update/preview, but still shows in the edit mode of WordPress.

**Comment by danipowers** [comment]
To add to this, I put an image in and aligned it today and it did align, however, when it has the orange frame style applied to it, the frame doesn't stick with the image frame. Screenshot to show an example below.
![Screen Shot 2022-01-26 at 2 27 12 PM](https://user-images.githubusercontent.com/97196996/151232691-1d7e3ded-76c1-4024-93f4-26925be39d5e.png)

**Comment by pikemurdy** [comment]
Figured this one out. But it's in the framework. So I'm moving this issue there.
