### ISSUE TITLE
Replace Smokey image

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utksds-plugin#50]
Replace this image:
https://github.com/utkwdn/utksds-plugin/blob/main/src/img/smokey-x-01.png

All the Smokey images from that shoot have a license on them.

**Comment by spworky** [comment]
@pikemurdy That image is one that Stephen Bridges shot. I color tweaked it slightly to have the feel of the licensed one. I believe I had removed the licensed one from the pattern before we added it. [Asset bank #288777](https://assetbank.ath.utk.edu/asset-bank/action/viewDownloadSharedAsset?download=50587763583961576a766347317845504375436e68673d3d&asset=646472526639567962583757614a6b6d48772f3764773d3d)
