### ISSUE TITLE
Content strip does not change colors in the editor

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utksds-plugin#6]

**Comment by danipowers** [comment]
This may be the same thing: But assigning the content to Smokey creates blue. UT Orange works as expected though.

**Comment by danipowers** [comment]
<img width="1247" alt="Screen Shot 2022-01-12 at 11 20 17 AM" src="https://user-images.githubusercontent.com/97196996/149179673-4e35dfd1-142e-4af6-9f60-967209c66509.png">
<img width="1379" alt="Screen Shot 2022-01-12 at 11 20 30 AM" src="https://user-images.githubusercontent.com/97196996/149179678-50a73513-15c2-445a-b030-63c1c05e0ada.png">
